version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:5000"
    environment:
      DB_SERVER: your-db-server
      DB_NAME: SeatReservation

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"